project/api/models.py
from datetime import datetime
from random import randint

from dateutil import parser
from sqlalchemy import func

from project import db

players_to_trainings = db.Table(
    "players_to_trainings",
    db.Column("player_id", db.Integer, db.ForeignKey("players.id")),
    db.Column("training_id", db.Integer, db.ForeignKey("trainings.id")),
)


class Player(db.Model):
    __tablename__ = "players"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    fname = db.Column(db.String(64), nullable=False)
    lname = db.Column(db.String(64), nullable=False)
    email = db.Column(db.String(128), nullable=False, unique=True)
    club_id = db.Column(db.Integer, db.ForeignKey("clubs.id"))
    trainings = db.relationship("Training", secondary=players_to_trainings)

    def __init__(self, fname, lname, email):
        self.fname = fname
        self.lname = lname
        # TODO: fix this below
        if email is None:
            dummy_email = (
                f"{self.fname.lower()}.{self.lname.lower()}{randint(0,100)}@vizihoki.hu"
            )
            self.email = dummy_email
        else:
            self.email = email

    def __repr__(self):
        return (
            f"Player(fname={self.fname!r}, lname={self.lname!r}, email={self.email!r})"
        )

    def __str__(self):
        return f"{self.fname} {self.lname}"

    def get_training_percentage(self):
        return (
            100
            * len(self.trainings)
            / db.session.query(func.count(Training.id)).scalar()
        )


class Training(db.Model):
    __tablename__ = "trainings"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    date = db.Column(db.DateTime())
    club_id = db.Column(db.Integer, db.ForeignKey("clubs.id"))
    players = db.relationship("Player", secondary=players_to_trainings)

    def __init__(self, club_id=None, date=None, player_ids=None):
        self.player_ids = player_ids or []
        self.players = [Player.query.get(p_id) for p_id in self.player_ids]
        self.club_id = club_id
        if isinstance(date, str):
            self.date = parser.parse(date)
        elif isinstance(date, datetime):
            self.date = date
        else:
            self.date = datetime.now()

    def __repr__(self):
        return (
            f"Training(club_id={self.club_id!r},"
            f"date={self.date!r}, players={self.players!r})"
        )

    def __str__(self):
        return f"Training({self.date.isoformat()}, {len(self.players)} players)"


class Club(db.Model):
    __tablename__ = "clubs"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128), nullable=False, unique=True)
    players = db.relationship("Player", backref="club")
    trainings = db.relationship("Training", backref="club")

    def __init__(self, name, player_ids=None, training_ids=None):
        self.name = name
        self.players = (
            [Player.query.get(int(p_id)) for p_id in player_ids] if player_ids else []
        )
        self.trainings = (
            [Training.query.get(int(t_id)) for t_id in training_ids]
            if training_ids
            else []
        )

    def __repr__(self):
        return (
            f"Club(name={self.name!r}",
            f"players={self.players!r}",
            f"trainings={self.trainings!r})",
        )

project/views/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class RegisterPlayerForm(FlaskForm):
    fname = StringField("Keresztnév", validators=[DataRequired()])
    lname = StringField("Vezetéknév", validators=[DataRequired()])

project/__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app(script_info=None):
    app = Flask(__name__)

    app_settings = os.getenv("APP_SETTINGS")
    app.config.from_object(app_settings)

    db.init_app(app)

    # views
    from project.views.index import index_blueprint
    from project.views.tranings import trainings_view
    from project.views.players import players_view

    # api
    from project.api.ping import ping_blueprint
    from project.api.players import players_api
    from project.api.clubs import clubs_blueprint
    from project.api.trainings import trainings_api

    app.register_blueprint(index_blueprint)
    app.register_blueprint(trainings_view)
    app.register_blueprint(players_view)

    app.register_blueprint(ping_blueprint)
    app.register_blueprint(players_api)
    app.register_blueprint(clubs_blueprint)
    app.register_blueprint(trainings_api)

    from project.api.models import Player, Training, Club

    @app.shell_context_processor
    def ctx():
        return {
            "app": app,
            "db": db,
            "Player": Player,
            "Training": Training,
            "Club": Club,
        }

    return app

project/gui/views.py
from flask import Blueprint, render_template

from project.api.models import Training, Player


stats_blueprint = Blueprint("views", __name__, url_prefix="/stats")


@stats_blueprint.route("/trainings", methods=["GET"])
def trainings():
    return render_template("trainings.html", trainings=Training.query.all())


@stats_blueprint.route("/players", methods=["GET"])
def players():
    raw_players = Player.query.all()
    # shitty counter but the number is low, so...
    num_of_trainings = len(Training.query.all())
    players = []
    for p in raw_players:
        players.append({
            "name": f"{p.lname} {p.fname}",
            "num_trainings": len(p.trainings),
            "training_percentage": int(len(p.trainings) / num_of_trainings * 100)
        })
    return render_template("players.html", players=players)

project/views/index.py
from flask import Blueprint, render_template


index_blueprint = Blueprint("index", __name__)


@index_blueprint.route("/", methods=["GET"])
@index_blueprint.route("/home", methods=["GET"])
def index():
    return render_template("index.html")

project/views/players.py
from flask import Blueprint, render_template, redirect, url_for

from project import db
from project.api.models import Player, Training
from project.views.forms import RegisterPlayerForm


players_view = Blueprint("players", __name__, url_prefix="/players")


@players_view.route("/", methods=["get"])
def all_players():
    players = prepare_players_dataobject()
    return render_template("players.html", players=players)


@players_view.route("/<int:player_id>")
def get_single_player(player_id: int):
    player = Player.query.filter_by(id=player_id).first()
    if not player_id:
        return render_template("404.html"), 404
    training_percentage = int(player.get_training_percentage())
    return render_template(
        "single_player.html", player=player, training_percentage=training_percentage
    )


@players_view.route("/add", methods=["POST", "GET"])
def add_player():
    form = RegisterPlayerForm()
    if form.validate_on_submit():
        player = Player(fname=form.fname.data, lname=form.lname.data, email=None)
        db.session.add(player)
        db.session.commit()
        return redirect(url_for("players.get_single_player", player_id=player.id))
    return render_template("add_player.html", form=form)


def prepare_players_dataobject() -> list:
    all_players = Player.query.all()
    num_of_trainings = len(Training.query.all())
    players = []
    for player in all_players:
        train_perc = calc_training_perc(len(player.trainings), num_of_trainings)
        color = determine_color(train_perc)
        players.append(
            {
                "name": f"{player.lname} {player.fname}",
                "num_trainings": len(player.trainings),
                "training_percentage": train_perc,
                # color shouldn't be determined in backend, but...
                "chart_color": color,
            }
        )
    players.sort(key=lambda p: p["name"])
    return players


def calc_training_perc(players_num: int, all_training_num: int) -> int:
    return int(players_num / all_training_num * 100)


# This really doesn't belong here, please learn javascript :'(
def determine_color(percentage: int) -> str:
    values = [(30, "is-danger"), (60, "is-warning"), (90, "is-success")]
    for perc, color in values:
        if percentage < perc:
            return color
    return "is-link"

project/views/tranings.py
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for

from project import db
from project.api.models import Training
from project.views.utils import get_all_players_sorted, sort_player_list_by_name


trainings_view = Blueprint("trainings", __name__, url_prefix="/trainings")


@trainings_view.route("/", methods=["get"])
def all_trainings():
    return render_template("trainings.html", trainings=Training.query.all())


@trainings_view.route("/add", methods=["get", "post"])
def add_training():
    players = get_all_players_sorted()
    present_pattern = "players-present"
    if request.method == "POST":
        players_present = request.values.getlist(present_pattern)
        current_date = datetime.today()
        db.session.add(
            Training(club_id=1, date=current_date, player_ids=players_present)
        )
        db.session.commit()
        return redirect(url_for("trainings.all_trainings"))
    return render_template(
        "add_training.html", present_pattern=present_pattern, players=players
    )


@trainings_view.route("/<int:training_id>")
def get_single_training(training_id: int):
    training = Training.query.filter_by(id=training_id).first()
    if not training:
        return render_template("404.html"), 404
    players = sort_player_list_by_name(training.players)
    return render_template("single_training.html", players=players, training=training)

project/views/utils.py
from project.api.models import Player


def get_all_players_sorted() -> list:
    return Player.query.order_by(Player.lname)


def sort_player_list_by_name(players: list) -> list:
    return sorted(players, key=lambda p: p.lname)

project/templates/add_player.html
{% extends 'base.html' %}

{% block content %}
<div class="content is-medium">
    <h2>Játékos hozzáadása</h2>
    <div class="container is-5">
        <form action="{{ url_for('players.add_player') }}" method="POST">
            {{ form.hidden_tag() }}
            {{ form.lname.label }} {{ form.lname(size=24, class_="input", style="margin-top: 5px") }}<br>
            {{ form.fname.label }} {{ form.fname(size=24, class_="input", style="margin-top: 5px") }}<br>
            <input style="margin-top: 10px;" class="button is-success" type="submit" value="Hozzáad">
        </form>
    </div>
</div>
{% endblock content %}

project/templates/add_training.html
{% extends 'base.html' %}

{% block content %}
<form action={{ url_for('trainings.add_training')}} method="post">
    <table class="table">
        {% for player in players %}
        <tbody>
            <td>
                <label class="checkbox">
                    <input type="checkbox" value="{{ player.id }}" name="{{ present_pattern }}">
                    {{ player.lname }} {{ player.fname }}
                </label>
            </td>
        </tbody>

        {% endfor %}
    </table>
    <input type="submit" value="Hozzáad" class="button is-success">
</form>
{% endblock content %}

project/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script type="text/javascript" src="/static/js/menus.js"></script>
</head>

<nav class="navbar is-info" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href={{ url_for("index.index") }}>
            <img src="/static/images/logo.png" width="40" height="80">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href={{ url_for("index.index") }}>
                Főoldal
            </a>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Statisztika
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item" href={{ url_for("trainings.all_trainings") }}>
                        Edzési
                    </a>
                    <a class="navbar-item" href={{ url_for("players.all_players") }}>
                        Játékos
                    </a>
                </div>
            </div>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Új
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item" href="{{ url_for('trainings.add_training') }}">
                        Edzés
                    </a>
                    <a class="navbar-item" href="{{ url_for('players.add_player') }}">
                        Játékos
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>

<body>
    <section class="section">
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </section>
</body>

</html>

project/templates/index.html
{% extends 'base.html' %}

{% block title %}
UWHome
{% endblock title %}

{% block content %}
<b>Üdv az erősen fejlesztés alatt lévő honlapon!</b>
<h3>Hasznosabb linkek</h3>
<ul>
    <li><a href={{ url_for('trainings.all_trainings') }}>Edzés statisztikák</a></li>
    <li><a href={{ url_for('players.all_players') }}>Játékos statisztikák</a></li>
</ul>
{% endblock content %}

project/templates/players.html
{% extends 'base.html' %}
{% block title %}
Játékosok
{% endblock title %}
{% block content %}
<table class="table is-striped is-narrow">
    <thead>
        <tr>
            <th>Név</th>
            <th>Edzések száma</th>
            <th align="center">Részvételi arány</th>
            <th align="center">%</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Név</th>
            <th>Edzések száma</th>
            <th align="center">Részvételi arány</th>
            <th align="center">%</th>
        </tr>
    </tfoot>
    <tbody>
        {% for player in players %}
        <tr>
            <td> {{ player.name }}</td>
            <td align="center"> {{ player.num_trainings }}</td>
            <td align="center"><progress class="progress is-small {{ player.chart_color }}"
                    value={{ player.training_percentage }} max=100>{{ player.training_percentage }}%</progress></td>
            <td align="center">{{ player.training_percentage }}%</progress></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

project/templates/single_player.html
{% extends 'base.html' %}

{% block content %}
<div class="content is-medium">
    <h3>{{ player.lname }} {{player.fname}}</h3>
    <h4>Edzési statisztika</h4>
    <p>Részvételi arány: {{ training_percentage }}%. </p>
    <progress class="progress" value={{ training_percentage }} max=100>{{ training_percentage }}%</progress>
    {% endblock content %}
</div>

project/templates/single_training.html
{% extends 'base.html' %}

{% block content %}
<div class="content is-medium">
    <h3>{{ training.date.strftime('%Y-%m-%d') }}</h3>
    <div class="list">
        {% for player in players %}
        <a class="list-item" href="{{ url_for('players.get_single_player', player_id=player.id) }}">
            {{ player.lname }} {{ player.fname }}
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}

project/templates/trainings.html
{% extends 'base.html' %}
{% block title %}
Edzések
{% endblock title %}
{% block content %}
<table class="table is-striped">
    <thead>
        <tr>
            <th>Időpont</th>
            <th>Játékosok száma</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Időpont</th>
            <th>Játékosok száma</th>
        </tr>
    </tfoot>
    <tbody>
        {% for training in trainings %}
        <tr>
            <th> <a href="{{ url_for('trainings.get_single_training', training_id=training.id)}}">
                    {{ training.date.strftime('%Y-%m-%d') }} </a></th>
            <th align=" center"> {{ training.players | length }} </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}